---
- hosts: workers
  remote_user: ubuntu
  become: yes

  tasks:
  - name: ensure locale is en_US.UTF-8
    locale_gen:
      name: en_US.UTF-8
      state: present

  - name: install docker requirements
    apt: pkg={{ item }} state=installed
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-pip

  - name: export LC_ALL, --upgrade setuptools
    shell: bash export LC_ALL=C; pip install --upgrade setuptools

  - name: add to trusted keys
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: update trusted keys
    command: apt-key update

  - name: add docker official apt repository
    apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present

  - name: install docker-ce
    apt: pkg=docker-ce update_cache=yes state=installed

  - name: install docker-py
    pip:
      name: docker

  - name: create /etc/systemd/system/docker.service.d if it doesn't exist
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory

  - name: create /etc/systemd/system/docker.service.d/custom.conf
    file:
      path: /etc/systemd/system/docker.service.d/custom.conf
      state: touch

  - name: modify docker.service to open DOCKER API
    blockinfile:
      path: /etc/systemd/system/docker.service.d/custom.conf
      block: |
       [Service]
       ExecStart=
       ExecStart=/usr/bin/dockerd  -H tcp://0.0.0.0:2375 -H unix://var/run/docker.sock

  - name: restart docker.service on nodes
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker

